int detectDust(int dustInput);
void detectObstacleDirection(int obstacleArray[]);
int dustSensorInterface();
int frontSensorInterface();
int leftSensorInterface();
int rightSensorInterface();
int performActionByMode(int d, int f, int l, int r, int mode);
void performActionForward(int f, int l, int r, int mode);
void performActionBackward(int f, int l, int r, int mode);
void turnFirstActionFromForward(int f, int l, int r, int mode);
void turnFirstActionFromBackward(int f, int l, int r, int mode);
void turnSecondAction();
char* cleanerSwitch(int command);
char* powerUpCleaner();
void turn(int f, int l, int r, int mode);
char* turnLeft();
char* turnRight();
char* moveForward(int command);
char* moveBackward(int command);